User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonDiscoveryModulecf'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'pythonSurveyNotification'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'ShowExtensionSurveyPrompt - enabled'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'DeprecatePythonPath - experiment'
> pyenv root
> conda --version
> python3.7 ~/.vscode-server/extensions/ms-python.python-2021.5.829140558/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode-server/extensions/ms-python.python-2021.5.829140558/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode-server/extensions/ms-python.python-2021.5.829140558/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode-server/extensions/ms-python.python-2021.5.829140558/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-server/extensions/ms-python.python-2021.5.829140558/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /usr/bin/python3 ~/.vscode-server/extensions/ms-python.python-2021.5.829140558/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
Python interpreter path: /usr/bin/python3
> pyenv root
> pyenv root
Starting Pylance language server.
Error 2021-05-13 22:11:40: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://ssh-remote+52.11.206.32/home/ubuntu/ChrisServer/.vscode/settings.json' (Error: Unable to resolve non-existing file 'vscode-remote://ssh-remote+52.11.206.32/home/ubuntu/ChrisServer/.vscode/settings.json')
	at _handleError (/home/ubuntu/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/out/vs/server/remoteExtensionHostProcess.js:86:154942)
	at async y.readText (/home/ubuntu/.vscode-server/extensions/ms-python.python-2021.5.829140558/out/client/extension.js:9:344717)
	at async p.doesFileNeedToBeFixed (/home/ubuntu/.vscode-server/extensions/ms-python.python-2021.5.829140558/out/client/extension.js:59:581560)
	at async /home/ubuntu/.vscode-server/extensions/ms-python.python-2021.5.829140558/out/client/extension.js:59:580687
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (/home/ubuntu/.vscode-server/extensions/ms-python.python-2021.5.829140558/out/client/extension.js:59:580633)
	at async p.updateTestSettings (/home/ubuntu/.vscode-server/extensions/ms-python.python-2021.5.829140558/out/client/extension.js:59:580260)] {
  code: 'FileNotFound'
}
Error 2021-05-13 22:11:40: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://ssh-remote+52.11.206.32/home/ubuntu/.config/Code/User/settings.json' (Error: Unable to resolve non-existing file 'vscode-remote://ssh-remote+52.11.206.32/home/ubuntu/.config/Code/User/settings.json')
	at _handleError (/home/ubuntu/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/out/vs/server/remoteExtensionHostProcess.js:86:154942)
	at async y.readText (/home/ubuntu/.vscode-server/extensions/ms-python.python-2021.5.829140558/out/client/extension.js:9:344717)
	at async p.doesFileNeedToBeFixed (/home/ubuntu/.vscode-server/extensions/ms-python.python-2021.5.829140558/out/client/extension.js:59:581560)
	at async /home/ubuntu/.vscode-server/extensions/ms-python.python-2021.5.829140558/out/client/extension.js:59:580687
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/home/ubuntu/.vscode-server/extensions/ms-python.python-2021.5.829140558/out/client/extension.js:59:580633)
	at async p.updateTestSettings (/home/ubuntu/.vscode-server/extensions/ms-python.python-2021.5.829140558/out/client/extension.js:59:580260)] {
  code: 'FileNotFound'
}
> conda --version
